version: "3.7"
services:
  trac:
    build: .
    # image: pabloszx/trac-v2
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DOMAIN: ${DOMAIN}
      SECRET: ${SECRET}
      COOKIE_SECRET: ${COOKIE_SECRET}
      # NODE_ENV: production
      NODE_ENV: test
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      EMAIL_ADDRESS: ${EMAIL_ADDRESS}
      EMAIL_ADDRESS_NAME: ${EMAIL_ADDRESS_NAME}
      EMAIL_ADDRESS_REPLY_TO: ${EMAIL_ADDRESS_REPLY_TO}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      # ANONYMOUS_ID_SERVICE: ${ANONYMOUS_ID_SERVICE}
      # SHOW_GRAPHQL_API: true
